/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveArchiveIdRouteImport } from './routes/archive/$archiveId'
import { Route as ArchiveArchiveIdIndexRouteImport } from './routes/archive/$archiveId/index'
import { Route as ArchiveArchiveIdFileFileNameRouteImport } from './routes/archive/$archiveId/file/$fileName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveArchiveIdRoute = ArchiveArchiveIdRouteImport.update({
  id: '/archive/$archiveId',
  path: '/archive/$archiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveArchiveIdIndexRoute = ArchiveArchiveIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArchiveArchiveIdRoute,
} as any)
const ArchiveArchiveIdFileFileNameRoute =
  ArchiveArchiveIdFileFileNameRouteImport.update({
    id: '/file/$fileName',
    path: '/file/$fileName',
    getParentRoute: () => ArchiveArchiveIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive/$archiveId': typeof ArchiveArchiveIdRouteWithChildren
  '/archive/$archiveId/': typeof ArchiveArchiveIdIndexRoute
  '/archive/$archiveId/file/$fileName': typeof ArchiveArchiveIdFileFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive/$archiveId': typeof ArchiveArchiveIdIndexRoute
  '/archive/$archiveId/file/$fileName': typeof ArchiveArchiveIdFileFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive/$archiveId': typeof ArchiveArchiveIdRouteWithChildren
  '/archive/$archiveId/': typeof ArchiveArchiveIdIndexRoute
  '/archive/$archiveId/file/$fileName': typeof ArchiveArchiveIdFileFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive/$archiveId'
    | '/archive/$archiveId/'
    | '/archive/$archiveId/file/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archive/$archiveId' | '/archive/$archiveId/file/$fileName'
  id:
    | '__root__'
    | '/'
    | '/archive/$archiveId'
    | '/archive/$archiveId/'
    | '/archive/$archiveId/file/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveArchiveIdRoute: typeof ArchiveArchiveIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$archiveId': {
      id: '/archive/$archiveId'
      path: '/archive/$archiveId'
      fullPath: '/archive/$archiveId'
      preLoaderRoute: typeof ArchiveArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$archiveId/': {
      id: '/archive/$archiveId/'
      path: '/'
      fullPath: '/archive/$archiveId/'
      preLoaderRoute: typeof ArchiveArchiveIdIndexRouteImport
      parentRoute: typeof ArchiveArchiveIdRoute
    }
    '/archive/$archiveId/file/$fileName': {
      id: '/archive/$archiveId/file/$fileName'
      path: '/file/$fileName'
      fullPath: '/archive/$archiveId/file/$fileName'
      preLoaderRoute: typeof ArchiveArchiveIdFileFileNameRouteImport
      parentRoute: typeof ArchiveArchiveIdRoute
    }
  }
}

interface ArchiveArchiveIdRouteChildren {
  ArchiveArchiveIdIndexRoute: typeof ArchiveArchiveIdIndexRoute
  ArchiveArchiveIdFileFileNameRoute: typeof ArchiveArchiveIdFileFileNameRoute
}

const ArchiveArchiveIdRouteChildren: ArchiveArchiveIdRouteChildren = {
  ArchiveArchiveIdIndexRoute: ArchiveArchiveIdIndexRoute,
  ArchiveArchiveIdFileFileNameRoute: ArchiveArchiveIdFileFileNameRoute,
}

const ArchiveArchiveIdRouteWithChildren =
  ArchiveArchiveIdRoute._addFileChildren(ArchiveArchiveIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveArchiveIdRoute: ArchiveArchiveIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
